import os

# all_datasets = ["arxiv_dataset", "claim_stance_topic", "argument_topic", "unfair_tos", "clinc150",'cuad',
#                 'head_qa', "20_newsgroup", "banking77",
#                  "contract_nli", "dbpedia", "ledgar",
#                 "news_category_classification_headline"]
from collections import defaultdict

all_datasets = ["arxiv_dataset", "claim_stance_topic", "argument_topic", "unfair_tos", "clinc150", 'cuad',
                'head_qa', "20_newsgroup", "banking77",
                "contract_nli", "dbpedia", "ledgar",
                "news_category_classification_headline", "CFPB_issue", "eli5_category",
                "financial_tweets", "law_stack_exchange", "legal_advice_reddit",
                "massive", "q2c_nda_eho", "schema_guided_dstc8_class_name", "SEC_10k", "wizard_of_wikipedia",
                "wiki_law_weak", "wiki_people_weak", "medical_abstracts"]  #

mvp_v0_2_datasets = ["arxiv_dataset", "claim_stance_topic", "argument_topic", "unfair_tos", "clinc150", 'cuad',
                    'head_qa', "20_newsgroup", "banking77",
                    "contract_nli", "dbpedia", "ledgar",
                    "news_category_classification_headline"]

mvp_v0_2_5_datasets = ["CFPB_Product",  "q2c_nda_eho", "SEC_10k", "claim_stance_topic",
                       "argument_topic", "unfair_tos", "clinc150", 'cuad',
                    'head_qa', "20_newsgroup", "banking77",
                    "contract_nli", "dbpedia", "ledgar",
                    "news_category_classification_headline"]

mvp_v0_2_5_datasets_mc = ["CFPB_Product", "SEC_10k", "claim_stance_topic", "argument_topic", "clinc150",
                          "20_newsgroup", "banking77", "ledgar", "news_category_classification_headline", "dbpedia", "head_qa"]


mvp_mc_folds = [["banking77", 'head_qa', "20_newsgroup"],
             ["ledgar", "SEC_10k", "argument_topic",  "dbpedia"],
             ["CFPB_Product", "claim_stance_topic", "clinc150", "news_category_classification_headline"]]

receipe_2_datasets = ["CFPB_Product", "SEC_10k", "claim_stance_topic", "argument_topic", "clinc150",
                          "20_newsgroup", "banking77", "ledgar", "news_category_classification_headline", "watson_sentiment",
                          'q2c-india']


mvp_folds = [["unfair_tos", "q2c_nda_eho", "banking77", 'head_qa', "20_newsgroup"],
             ['cuad', "ledgar", "SEC_10k", "argument_topic",  "dbpedia"],
             ["contract_nli", "CFPB_Product", "claim_stance_topic", "clinc150", "news_category_classification_headline"]]

mvp_v0_3_datasets = ["arxiv_dataset", "claim_stance_topic", "argument_topic", "unfair_tos", "clinc150", 'cuad',
                    'head_qa', "20_newsgroup", "banking77",
                    "contract_nli", "dbpedia", "ledgar",
                    "news_category_classification_headline", "CFPB_Product", "massive", "medical_abstracts",
                     "q2c_nda_eho", "SEC_10k", "law_stack_exchange"]

ds_to_type = defaultdict(lambda: 'topical', {'stanford_large_movie_review': 'sentiment', 'tripadvisor_hotel_reviews': 'sentiment',
                                             'ecommerce_reviews': 'description', 'news_headlines_sarcasm_detection': 'description','imdb_movie_spoiler': 'description',
                                             'zero_shot_emotion': 'emotion', 'cola': 'description', 'trec': 'topical'}) #'sms_spam':'description', 'zero_shot_situation': 'topical'

def hypothesis_by_type(hypothesis, type):
    if type == 'topical':
        return hypothesis
    if type == "sentiment":
        return "This text has {} sentiment."
    if type == "emotion":
        return "This text expresses {}."
    if type == "description":
        return "This text is {}."

    raise Exception(f"Type {type} is not supported yet!")

additional_datasets = ["stanford_large_movie_review", "tripadvisor_hotel_reviews", "news_headlines_sarcasm_detection", "imdb_movie_spoiler",
                       "zero_shot_emotion", "cola", "trec"]

domains = {"arxiv_dataset": "science", "claim_stance_topic": "general", "argument_topic": "general",
           "unfair_tos": "legal",
           "clinc150": "general", "cuad": "legal", "head_qa": "medical", "20_newsgroup": "general",
           "banking77": "finance", "contract_nli": "legal",
           "dbpedia": "general", "ledgar": "legal", "news_category_classification_headline": "news",
           "CFPB_Product": "finance",
           "eli5_category": "general", "financial_tweets": "finance", "law_stack_exchange": "legal",
           "legal_advice_reddit": "legal",
           "massive": "intents", "medical_abstracts": "medical", "ag_news": "news", "yahoo_answers": "general",
           "xglue": "news", "sentivent": "finance", "reuters21578": "finance"}

paper_folds = [["reuters21578", 'claim_stance_topic',
                'unfair_tos',
                'head_qa',
                'banking77',
                'ag_news',
                'yahoo_answers_topics'],
               ['argument_topic',
                'cuad',
                'dbpedia_14',
                'news_category_classification_headline',
                'eli5_category',
                'financial_tweets',
                'law_stack_exchange',
                'massive'],
                ['clinc150',
                 '20_newsgroups',
                 'contract_nli',
                 'ledgar',
                 'legal_advice_reddit',
                 'medical_abstracts',
                 'xglue',
                 'sentivent']]

EMNLP_open_source_folds = [["reuters21578", 'claim_stance_topic',
                'unfair_tos',
                'head_qa',
                'banking77',
                'ag_news',
                'yahoo_answers_topics'],
               ['argument_topic',
                'cuad',
                'dbpedia_14',
                'news_category_classification_headline',
                'law_stack_exchange',
                'massive'],
                ['clinc150',
                 '20_newsgroups',
                 'contract_nli',
                 'ledgar',
                 'medical_abstracts',
				 'financial_tweets',
                ]]
    
# domain folds
folds_domain_out = [["medical_abstracts", "head_qa"],
           ["unfair_tos", "cuad", "ledgar", "contract_nli", "legal_advice_reddit", "law_stack_exchange"],
           ["sentivent", "reuters21578", "banking77", "financial_tweets"],
           ["massive","20_newsgroup","claim_stance_topic","argument_topic","news_category_classification_headline",
            "eli5_category","dbpedia","yahoo_answers","ag_news","xglue","clinc150"]]

folds_as_dict = {d:i for i,l in enumerate(paper_folds) for d in l}

paper_datasets = ["claim_stance_topic", "argument_topic", "unfair_tos", "clinc150", 'cuad',
                  'head_qa', "20_newsgroup", "banking77",
                  "contract_nli", "dbpedia", "ledgar",
                  "news_category_classification_headline", "eli5_category",
                  "financial_tweets", "law_stack_exchange", "legal_advice_reddit",
                  "massive", "medical_abstracts", "ag_news", "yahoo_answers_topics", "xglue",
                  "sentivent", "reuters21578"]  # "CFPB_issue", "wiki_people_weak", "arxiv_dataset"
## arxiv_dataset removed because it has long texts with a lot of classes


non_flan_datasets = ["claim_stance_topic", "argument_topic", "unfair_tos", "clinc150", 'cuad',
                   "20_newsgroup", "banking77",
                  "contract_nli", "ledgar",
                  "news_category_classification_headline", "eli5_category",
                  "financial_tweets", "law_stack_exchange", "legal_advice_reddit",
                  "massive", "medical_abstracts" "xglue",
                  "sentivent", "reuters21578"]

seq_length_512_datasets = ["claim_stance_topic", "argument_topic", "unfair_tos", 'cuad',
                   "banking77",
                  "contract_nli",
                  "news_category_classification_headline", "eli5_category",
                  "financial_tweets", "law_stack_exchange",
                  "massive",
                  "sentivent", "reuters21578"]

seq_length_2048_datasets = ["clinc150",
                   "20_newsgroup",  "ledgar",
                  "legal_advice_reddit",
                 "medical_abstracts", "xglue"]

legal_datasets = ["contract_nli", "ledgar", "cuad", "unfair_tos"]

sentiment_id2label = {0: "negative", 1: "positive", 2: "neutral"}
sentiment_label2id = {"negative": 0, "positive": 1, "neutral": 2}

big_sentiment_datasets = ["ALMR", "ALMS", "ALROT", "EMRED", "EMTED", "EMWTBOT", "FPB_75"]
all_sentiment_datasets = ["EMWVA", "EMMOVDLG", "EMAVA", "EMSPEECH",
                          "EMVOG", "EMARC", "EMRED", "ALROT", "EMPUBCROWD", "EMPAY",
                          "ALMS", "ALMR", "EMTED", "EMWTBOT", "FPB_75"]

multilabel_datasets = ["contract_nli","cuad","reuters21578","sentivent","unfair_tos", "q2c_nda_eho"]

held_out_datasets = {"law_stack_exchange", "cuad_mc", "q2c_nda_eho_mc"}

clean_topics = {
    'yahoo_answers': {"Sports": "sports",
                      "Health": "health",
                      "Family & Relationships": "family and relationships",
                      "Science & Mathematics": "science and mathematics",
                      "Education & Reference": "education and reference",
                      "Entertainment & Music": "entertainment and music",
                      "Society & Culture": "society and culture",
                      "Business & Finance": "business and finance’",
                      "Politics & Government": "politics and government",
                      "Computers & Internet": "computers and internet"
                      },

    'ag_news': {"World": "world", "Sci/Tech": "science and technology", "Sports": "sports",
                "Business": "business"},

    'dbpedia': {"Artist": "artist",
                "Plant": "plant", "Album": "album", "Animal": "animal",
                "MeanOfTransportation": "mean of transportation",
                "NaturalPlace": "natural place", "Athlete": "athlete", "OfficeHolder": "office holder",
                "Company": "company", "Film": "film", "EducationalInstitution": "educational institution",
                "WrittenWork": "written work", "Building": "building", "Village": "village"},

    '20_newsgroup': {
        'alt.atheism': 'atheism',
        'comp.graphics': 'computer graphics',
        'comp.os.ms-windows.misc': 'microsoft windows',
        'comp.sys.ibm.pc.hardware': 'pc hardware',
        'comp.sys.mac.hardware': 'mac hardware',
        'comp.windows.x': 'windows x',
        'misc.forsale': 'for sale',
        'rec.autos': 'cars',
        'rec.motorcycles': 'motorcycles',
        'rec.sport.baseball': 'baseball',
        'rec.sport.hockey': 'hockey',
        'sci.crypt': 'cryptography',
        'sci.electronics': 'electronics',
        'sci.med': 'medicine',
        'sci.space': 'space',
        'soc.religion.christian': 'christianity',
        'talk.politics.guns': 'guns',
        'talk.politics.mideast': 'middle east',
        'talk.politics.misc': 'politics',
        'talk.religion.misc': 'religion'
    },
    'news_category_classification': {
        'IMPACT': 'impact',
        'STYLE & BEAUTY': 'style and beauty',
        'PARENTING': 'parenting',
        'WORLD NEWS': 'world news',
        'FIFTY': 'fifty',
        'MEDIA': 'media',
        'U.S. NEWS': 'u.s. news',
        'WORLDPOST': 'world news',
        'COMEDY': 'comedy',
        'ENTERTAINMENT': 'entertainment',
        'LATINO VOICES': 'latino voices',
        'GOOD NEWS': 'good news',
        'BUSINESS': 'business',
        'WELLNESS': 'wellness',
        'SCIENCE': 'science',
        'EDUCATION': 'education',
        'SPORTS': 'sports',
        'BLACK VOICES': 'black voices',
        'WEDDINGS': 'weddings',
        'POLITICS': 'politics',
        'PARENTS': 'parents',
        'CULTURE & ARTS': 'culture and arts',
        'THE WORLDPOST': 'world news',
        'ARTS': 'arts',
        'TASTE': 'taste',
        'FOOD & DRINK': 'food and drink',
        'WOMEN': 'women',
        'TECH': 'tech',
        'DIVORCE': 'divorce',
        'TRAVEL': 'travel',
        'MONEY': 'money',
        'ENVIRONMENT': 'environment',
        'ARTS & CULTURE': 'arts and culture',
        'STYLE': 'style',
        'HEALTHY LIVING': 'healthy living',
        'WEIRD NEWS': 'weird news',
        'CRIME': 'crime',
        'HOME & LIVING': 'home and living',
        'COLLEGE': 'college',
        'QUEER VOICES': 'queer voices',
        'GREEN': 'green',
        'RELIGION': 'religion',
    },
    "contract_nli":
        {

            "nda-11":
                "no reverse engineering",
            "nda-16": "return of confidential information",

            "nda-15": "no licensing",

            "nda-10": "confidentiality of agreement",

            "nda-2": "none-inclusion of non-technical information",

            "nda-1": "explicit identification",

            "nda-19": "survival of obligations",

            "nda-12": "permissible development of similar information",

            "nda-20": "permissible post-agreement possession",

            "nda-3": "inclusion of verbally conveyed information",

            "nda-18": "no solicitation",

            "nda-7": "sharing with third-parties",

            "nda-17": "permissible copy",

            "nda-8": "notice on compelled disclosure",

            "nda-13": "permissible acquirement of similar information",

            "nda-5": "sharing with employees",

            "nda-4": "limited use",
        },

    'banking77': {0: 'activating my card', 1: 'age limit', 2: 'apple pay or google pay', 3: 'atm support',
                  4: 'automatic top up', 5: 'balance that has not been updated after a bank transfer',
                  6: 'balance that has not been updated after cheque or cash deposit',
                  7: 'beneficiary who is not allowed', 8: 'canceling a transfer', 9: 'card that is about to expire',
                  10: 'card acceptance', 11: 'card arrival', 12: 'card delivery estimation', 13: 'card linking',
                  14: 'card not working', 15: 'card payment fee that was charged', 16: 'card payment not recognised',
                  17: 'card payment wrong exchange rate', 18: 'card swallowed', 19: 'cash withdrawal charge',
                  20: 'cash withdrawal not recognised', 21: 'changing pin', 22: 'compromised card',
                  23: 'contactless not working', 24: 'country support', 25: 'declined card payment',
                  26: 'declined cash withdrawal', 27: 'declined transfer', 28: 'direct debit payment not recognised',
                  29: 'disposable card limits', 30: 'editing personal details', 31: 'exchange charge',
                  32: 'exchange rate', 33: 'exchange via app', 34: 'extra charge on statement', 35: 'failed transfer',
                  36: 'fiat currency support', 37: 'getting disposable virtual card', 38: 'getting physical card',
                  39: 'getting spare card', 40: 'getting virtual card', 41: 'lost or stolen card',
                  42: 'lost or stolen phone', 43: 'ordering physical card', 44: 'forgotten passcode',
                  45: 'pending card payment', 46: 'pending cash withdrawal', 47: 'pending top up',
                  48: 'pending transfer', 49: 'blocked pin', 50: 'receiving money', 51: 'refund not showing up',
                  52: 'refund request', 53: 'reverted card payment', 54: 'supported cards and currencies',
                  55: 'terminating account', 56: 'top up by bank transfer charge', 57: 'top up by card charge',
                  58: 'top up by cash or cheque', 59: 'failed top up', 60: 'top up limits', 61: 'top up reverted',
                  62: 'topping up by card', 63: 'transaction charged twice', 64: 'charged transfer fee',
                  65: 'transferring into account', 66: 'transfer not received by recipient', 67: 'transfer timing',
                  68: 'being unable to verify identity', 69: 'verifying my identity', 70: 'verifying source of funds',
                  71: 'verifying top up', 72: 'virtual card not working', 73: 'visa or mastercard',
                  74: 'why identity verification is necessary', 75: 'wrong amount of cash received',
                  76: 'wrong exchange rate for cash withdrawal'},
    'reuters21578': {'pet-chem': 'pet chem', 'income': 'income', 'strategic-metal': 'strategic metal', 'lei': 'lei',
                     'rand': 'rand', 'livestock': 'livestock', 'gold': 'gold', 'coconut-oil': 'coconut oil',
                     'rupiah': 'rupiah', 'nkr': 'nkr', 'oat': 'oat', 'propane': 'propane', 'saudriyal': 'saudriyal',
                     'sorghum': 'sorghum', 'tea': 'tea', 'cotton-oil': 'cotton oil', 'nat-gas': 'nat gas',
                     'fuel': 'fuel', 'citruspulp': 'citruspulp', 'nzdlr': 'nzdlr', 'stg': 'stg', 'sun-meal': 'sun meal',
                     'cruzado': 'cruzado', 'dfl': 'dfl', 'castorseed': 'castorseed', 'rice': 'rice',
                     'cornglutenfeed': 'cornglutenfeed', 'cpi': 'consumer price index', 'meal-feed': 'meal feed', 'wheat': 'wheat',
                     'crude': 'crude', 'gnp': 'gross national product', 'ship': 'ships', 'acq': 'acquisition', 'barley': 'barley',
                     'cottonseed': 'cottonseed', 'lin-oil': 'lin oil', 'corn-oil': 'corn oil', 'silver': 'silver',
                     'soy-meal': 'soy meal', 'tapioca': 'tapioca', 'orange': 'orange', 'plywood': 'plywood',
                     'lead': 'lead', 'tin': 'tin', 'f-cattle': 'f cattle', 'sfr': 'sfr', 'linseed': 'linseed',
                     'sugar': 'sugar', 'pork-belly': 'pork belly', 'jobs': 'jobs', 'naphtha': 'naphtha', 'rye': 'rye',
                     'lumber': 'lumber', 'interest': 'interest', 'dkr': 'dkr', 'platinum': 'platinum',
                     'money-supply': 'money supply', 'rape-meal': 'rape meal', 'coconut': 'coconut', 'gas': 'gas',
                     'heat': 'heat', 'retail': 'retail', 'ipi': 'ipi', 'ringgit': 'ringgit', 'copra-cake': 'copra cake',
                     'zinc': 'zinc', 'rapeseed': 'rapeseed', 'cpu': 'cpu', 'lit': 'lit', 'fishmeal': 'fishmeal',
                     'soy-oil': 'soy oil', 'veg-oil': 'vegetable oil', 'yen': 'yen', 'carcass': 'carcass',
                     'lin-meal': 'lin meal', 'red-bean': 'red bean', 'jet': 'jet', 'wpi': 'wpi',
                     'castor-oil': 'castor oil', 'copper': 'copper', 'coffee': 'coffee', 'wool': 'wool',
                     'cocoa': 'cocoa', 'groundnut-oil': 'groundnut oil', 'peseta': 'peseta', 'palm-oil': 'palm oil',
                     'dmk': 'dmk', 'bop': 'bop', 'l-cattle': 'l cattle', 'oilseed': 'oilseed',
                     'instal-debt': 'instal debt', 'grain': 'grain', 'iron-steel': 'iron steel', 'reserves': 'reserves',
                     'rubber': 'rubber', 'rape-oil': 'rape oil', 'housing': 'housing', 'inventories': 'inventories',
                     'potato': 'potato', 'hog': 'hog', 'trade': 'trade', 'earn': 'earnings', 'skr': 'skr',
                     'sun-oil': 'sun oil', 'palladium': 'palladium', 'sunseed': 'sunseed', 'dlr': 'dlr', 'can': 'can',
                     'soybean': 'soybean', 'corn': 'corn', 'cotton': 'cotton', 'austdlr': 'austdlr',
                     'palmkernel': 'palmkernel', 'groundnut': 'groundnut', 'alum': 'alum', 'money-fx': 'money foreign exchange',
                     'nickel': 'nickel'},
    'xglue': {8: 'video', 9: 'autos', 1: 'sports', 2: 'travel', 3: 'finance', 0: 'food and drink', 5: 'news',
              6: 'entertainment', 4: 'lifestyle', 7: 'health'},
    'cuad': {'Rofr/Rofo/Rofn': 'right of first refusal, right of first offer or right of first negotiation'},
    'finer-139': {0: 'o', 1: 'accrual for environmental loss contingencies',
                  2: 'acquired finite lived intangible assets weighted average useful life',
                  3: 'acquired finite lived intangible assets weighted average useful life',
                  4: 'allocated share based compensation expense', 5: 'amortization of financing costs',
                  6: 'amortization of intangible assets', 7: 'amortization of intangible assets',
                  8: 'antidilutive securities excluded from computation of earnings per share amount',
                  9: 'antidilutive securities excluded from computation of earnings per share amount',
                  10: 'area of real estate property', 11: 'area of real estate property',
                  12: 'asset impairment charges',
                  13: 'acquisition equity interests issued or issuable number of shares issued',
                  14: 'acquisition percentage of voting interests acquired',
                  15: 'acquisition percentage of voting interests acquired',
                  16: 'combination acquisition related costs', 17: 'combination consideration transferred1',
                  18: 'combination contingent consideration liability',
                  19: 'combination recognized identifiable assets acquired and liabilities assumed intangible assets other than goodwill',
                  20: 'combination recognized identifiable assets acquired and liabilities assumed intangibles',
                  21: 'capitalized contract cost amortization', 22: 'cash and cash equivalents fair value disclosure',
                  23: 'class of warrant or right exercise price of warrants or rights1',
                  24: 'common stock capital shares reserved for future issuance',
                  25: 'common stock dividends per share declared', 26: 'common stock par or stated value per share',
                  27: 'common stock shares authorized', 28: 'common stock shares authorized',
                  29: 'common stock shares outstanding', 30: 'concentration risk percentage1',
                  31: 'contract with customer liability', 32: 'contract with customer liability revenue recognized',
                  33: 'cumulative effect of new accounting principle in period of adoption',
                  34: 'debt instrument basis spread on variable rate1', 35: 'debt instrument carrying amount',
                  36: 'debt instrument convertible conversion price1', 37: 'debt instrument face amount',
                  38: 'debt instrument face amount', 39: 'debt instrument fair value',
                  40: 'debt instrument interest rate effective percentage',
                  41: 'debt instrument interest rate stated percentage', 42: 'debt instrument maturity date',
                  43: 'debt instrument maturity date', 44: 'debt instrument redemption price percentage',
                  45: 'debt instrument term', 46: 'debt instrument term', 47: 'debt instrument unamortized discount',
                  48: 'debt weighted average interest rate', 49: 'deferred finance costs gross',
                  50: 'deferred finance costs net', 51: 'defined benefit plan contributions by employer',
                  52: 'defined contribution plan cost recognized', 53: 'depreciation',
                  54: 'derivative fixed interest rate', 55: 'derivative notional amount',
                  56: 'disposal group including discontinued operation consideration',
                  57: 'effective income tax rate continuing operations',
                  58: 'effective income tax rate reconciliation at federal statutory income tax rate',
                  59: 'employee service share based compensation nonvested awards total compensation cost not yet recognized',
                  60: 'employee service share based compensation nonvested awards total compensation cost not yet recognized period for recognition1',
                  61: 'employee service share based compensation nonvested awards total compensation cost not yet recognized period for recognition1',
                  62: 'employee service share based compensation nonvested awards total compensation cost not yet recognized share based awards other than options',
                  63: 'employee service share based compensation tax benefit from compensation expense',
                  64: 'equity method investment ownership percentage',
                  65: 'equity method investment ownership percentage', 66: 'equity method investments',
                  67: 'finite lived intangible asset useful life', 68: 'finite lived intangible asset useful life',
                  69: 'gains losses on extinguishment of debt', 70: 'goodwill', 71: 'goodwill impairment loss',
                  72: 'guarantee obligations maximum exposure', 73: 'loss from equity method investments',
                  74: 'tax expense benefit', 75: 'expense', 76: 'expense debt', 77: 'lease and rental expense',
                  78: 'lessee operating lease renewal term', 79: 'lessee operating lease renewal term',
                  80: 'lessee operating lease term of contract', 81: 'lessee operating lease term of contract',
                  82: 'letters of credit outstanding amount', 83: 'line of credit',
                  84: 'line of credit facility commitment fee percentage',
                  85: 'line of credit facility current borrowing capacity',
                  86: 'line of credit facility interest rate at period end',
                  87: 'line of credit facility maximum borrowing capacity',
                  88: 'line of credit facility remaining borrowing capacity',
                  89: 'line of credit facility unused capacity commitment fee percentage', 90: 'long term debt',
                  91: 'long term debt fair value', 92: 'loss contingency accrual at carrying value',
                  93: 'loss contingency damages sought value', 94: 'loss contingency estimate of possible loss',
                  95: 'loss contingency pending claims number', 96: 'loss contingency pending claims number',
                  97: 'minority interest ownership percentage by noncontrolling owners',
                  98: 'minority interest ownership percentage by parent', 99: 'number of operating segments',
                  100: 'number of real estate properties', 101: 'number of real estate properties',
                  102: 'number of reportable segments', 103: 'operating lease cost', 104: 'operating lease expense',
                  105: 'operating lease liability', 106: 'operating lease payments',
                  107: 'operating lease right of use asset',
                  108: 'operating lease weighted average discount rate percent',
                  109: 'operating lease weighted average remaining lease term1',
                  110: 'operating lease weighted average remaining lease term1',
                  111: 'operating leases rent expense net', 112: 'operating loss carryforwards',
                  113: 'payments to acquire businesses gross',
                  114: 'payments to acquire businesses net of cash acquired',
                  115: 'preferred stock dividend rate percentage', 116: 'preferred stock shares authorized',
                  117: 'preferred stock shares authorized', 118: 'proceeds from issuance of common stock',
                  119: 'property plant and equipment useful life', 120: 'property plant and equipment useful life',
                  121: 'public utilities requested rate increase decrease amount',
                  122: 'related party transaction amounts of transaction',
                  123: 'related party transaction amounts of transaction',
                  124: 'related party transaction expenses from transactions with related party',
                  125: 'related party transaction expenses from transactions with related party',
                  126: 'repayments of debt', 127: 'restructuring and related cost expected cost1',
                  128: 'restructuring charges', 129: 'revenue from contract with customer excluding assessed tax',
                  130: 'revenue from contract with customer including assessed tax',
                  131: 'revenue from related parties', 132: 'revenue remaining performance obligation', 133: 'revenues',
                  134: 'sale of stock number of shares issued in transaction',
                  135: 'sale of stock number of shares issued in transaction', 136: 'sale of stock price per share',
                  137: 'share based compensation',
                  138: 'share based compensation arrangement by share based payment award award vesting period1',
                  139: 'share based compensation arrangement by share based payment award award vesting period1',
                  140: 'share based compensation arrangement by share based payment award equity instruments other than options grants in period',
                  141: 'share based compensation arrangement by share based payment award equity instruments other than options grants in period',
                  142: 'share based compensation arrangement by share based payment award equity instruments other than options grants in period weighted average grant date fair value',
                  143: 'share based compensation arrangement by share based payment award equity instruments other than options nonvested number',
                  144: 'share based compensation arrangement by share based payment award equity instruments other than options vested in period total fair value',
                  145: 'share based compensation arrangement by share based payment award number of shares authorized',
                  146: 'share based compensation arrangement by share based payment award number of shares authorized',
                  147: 'share based compensation arrangement by share based payment award number of shares available for grant',
                  148: 'share based compensation arrangement by share based payment award options exercises in period total intrinsic value',
                  149: 'share based compensation arrangement by share based payment award options grants in period gross',
                  150: 'share based compensation arrangement by share based payment award options grants in period weighted average grant date fair value',
                  151: 'share price',
                  152: 'sharebased compensation arrangement by sharebased payment award award vesting rights percentage',
                  153: 'sharebased compensation arrangement by sharebased payment award award vesting rights percentage',
                  154: 'sharebased compensation arrangement by sharebased payment award expiration period',
                  155: 'sharebased compensation arrangement by sharebased payment award expiration period',
                  156: 'stock issued during period shares new issues',
                  157: 'stock issued during period shares new issues',
                  158: 'stock repurchase program authorized amount1',
                  159: 'stock repurchase program remaining authorized repurchase amount1',
                  160: 'stock repurchased and retired during period shares',
                  161: 'stock repurchased during period shares', 162: 'stock repurchased during period shares',
                  163: 'supplemental information for property casualty insurance underwriters prior year claims and claims adjustment expense',
                  164: 'treasury stock acquired average cost per share', 165: 'treasury stock shares acquired',
                  166: 'treasury stock shares acquired', 167: 'treasury stock value acquired cost method',
                  168: 'unrecognized tax benefits',
                  169: 'unrecognized tax benefits that would impact effective tax rate',
                  170: 'deferred finance costs gross', 171: 'common stock par or stated value per share',
                  172: 'loss contingency estimate of possible loss', 173: 'defined contribution plan cost recognized',
                  174: 'debt instrument fair value', 175: 'contract with customer liability revenue recognized',
                  176: 'revenue remaining performance obligation',
                  177: 'employee service share based compensation nonvested awards total compensation cost not yet recognized',
                  178: 'debt instrument interest rate stated percentage', 179: 'operating loss carryforwards',
                  180: 'minority interest ownership percentage by noncontrolling owners', 181: 'expense',
                  182: 'long term debt', 183: 'share based compensation', 184: 'debt weighted average interest rate',
                  185: 'debt instrument carrying amount', 186: 'debt instrument convertible conversion price1',
                  187: 'tax expense benefit',
                  188: 'share based compensation arrangement by share based payment award options grants in period weighted average grant date fair value',
                  189: 'employee service share based compensation nonvested awards total compensation cost not yet recognized share based awards other than options',
                  190: 'equity method investments', 191: 'debt instrument unamortized discount',
                  192: 'gains losses on extinguishment of debt',
                  193: 'share based compensation arrangement by share based payment award number of shares available for grant',
                  194: 'combination recognized identifiable assets acquired and liabilities assumed intangible assets other than goodwill',
                  195: 'preferred stock dividend rate percentage',
                  196: 'revenue from contract with customer including assessed tax',
                  197: 'operating lease weighted average discount rate percent', 198: 'line of credit',
                  199: 'line of credit facility maximum borrowing capacity',
                  200: 'effective income tax rate reconciliation at federal statutory income tax rate',
                  201: 'line of credit facility commitment fee percentage',
                  202: 'combination consideration transferred1', 203: 'common stock dividends per share declared',
                  204: 'debt instrument basis spread on variable rate1',
                  205: 'disposal group including discontinued operation consideration',
                  206: 'share based compensation arrangement by share based payment award options grants in period gross',
                  207: 'common stock shares outstanding', 208: 'amortization of financing costs',
                  209: 'line of credit facility current borrowing capacity',
                  210: 'treasury stock value acquired cost method',
                  211: 'share based compensation arrangement by share based payment award equity instruments other than options nonvested number',
                  212: 'debt instrument interest rate effective percentage', 213: 'sale of stock price per share',
                  214: 'capitalized contract cost amortization', 215: 'restructuring charges',
                  216: 'share based compensation arrangement by share based payment award equity instruments other than options vested in period total fair value',
                  217: 'accrual for environmental loss contingencies',
                  218: 'cash and cash equivalents fair value disclosure', 219: 'proceeds from issuance of common stock',
                  220: 'revenues',
                  221: 'combination recognized identifiable assets acquired and liabilities assumed intangibles',
                  222: 'letters of credit outstanding amount',
                  223: 'share based compensation arrangement by share based payment award equity instruments other than options grants in period weighted average grant date fair value',
                  224: 'operating lease payments', 225: 'line of credit facility remaining borrowing capacity',
                  226: 'payments to acquire businesses gross', 227: 'treasury stock acquired average cost per share',
                  228: 'deferred finance costs net', 229: 'stock repurchase program authorized amount1',
                  230: 'expense debt', 231: 'contract with customer liability', 232: 'operating lease expense',
                  233: 'depreciation', 234: 'allocated share based compensation expense',
                  235: 'loss contingency accrual at carrying value',
                  236: 'line of credit facility unused capacity commitment fee percentage',
                  237: 'supplemental information for property casualty insurance underwriters prior year claims and claims adjustment expense',
                  238: 'operating lease liability', 239: 'revenue from related parties',
                  240: 'payments to acquire businesses net of cash acquired',
                  241: 'combination contingent consideration liability', 242: 'loss contingency damages sought value',
                  243: 'number of operating segments',
                  244: 'acquisition equity interests issued or issuable number of shares issued',
                  245: 'operating lease right of use asset', 246: 'combination acquisition related costs',
                  247: 'unrecognized tax benefits', 248: 'guarantee obligations maximum exposure',
                  249: 'restructuring and related cost expected cost1',
                  250: 'defined benefit plan contributions by employer', 251: 'operating lease cost',
                  252: 'derivative fixed interest rate', 253: 'goodwill', 254: 'goodwill impairment loss',
                  255: 'common stock capital shares reserved for future issuance',
                  256: 'stock repurchased and retired during period shares',
                  257: 'employee service share based compensation tax benefit from compensation expense',
                  258: 'loss from equity method investments', 259: 'number of reportable segments',
                  260: 'long term debt fair value', 261: 'repayments of debt', 262: 'concentration risk percentage1',
                  263: 'debt instrument redemption price percentage',
                  264: 'cumulative effect of new accounting principle in period of adoption', 265: 'share price',
                  266: 'unrecognized tax benefits that would impact effective tax rate',
                  267: 'share based compensation arrangement by share based payment award options exercises in period total intrinsic value',
                  268: 'effective income tax rate continuing operations',
                  269: 'revenue from contract with customer excluding assessed tax',
                  270: 'stock repurchase program remaining authorized repurchase amount1',
                  271: 'line of credit facility interest rate at period end',
                  272: 'class of warrant or right exercise price of warrants or rights1',
                  273: 'operating leases rent expense net', 274: 'lease and rental expense',
                  275: 'public utilities requested rate increase decrease amount',
                  276: 'minority interest ownership percentage by parent', 277: 'asset impairment charges',
                  278: 'derivative notional amount'},
    'unfair_tos': {0: 'limitation of liability', 1: 'unilateral termination', 2: 'unilateral change',
                   3: 'content removal', 4: 'contract by using', 5: 'choice of law', 6: 'jurisdiction',
                   7: 'arbitration'},
    'SEC_10k': {'employee_count': 'employee count', 'Foreign_Exchange_Impact': 'foreign exchange impact',
                'Key_Executives': 'key executives', 'Mergers_Acquisitions': 'mergers acquisitions',
                'Real_Estate': 'real estate', 'Sales_Dependency': 'sales dependency',
                'Supply_Chain_Dependency': 'supply chain dependency'},
    'massive': {0: 'getting date or time details', 1: 'changing hue light', 2: 'getting a transport ticket',
                3: 'getting a takeaway', 4: 'stock', 5: 'greeting', 6: 'event recommendation', 7: 'music dislikeness',
                8: 'turning off wemo', 9: 'cooking recipes', 10: 'currency', 11: 'transport traffic',
                12: 'quirky issues', 13: 'the weather', 14: 'turning up the volume', 15: 'adding email contact',
                16: 'takeaway order', 17: 'getting email contact', 18: 'increasing hue light',
                19: 'location recommendations', 20: 'playing an audio book', 21: 'creating or adding lists',
                22: 'the news', 23: 'getting alarm details', 24: 'turning wemo on', 25: 'joke', 26: 'definitions',
                27: 'social media', 28: 'music settings', 29: 'audio volume', 30: 'removing from calendar',
                31: 'dimming hue light', 32: 'getting calendar details', 33: 'sending en email', 34: 'cleaning',
                35: 'turning down volume', 36: 'playing the radio', 37: 'cooking details',
                38: 'converting date or time', 39: 'math', 40: 'turning off hue light', 41: 'turning on hue light',
                42: 'getting transport details', 43: 'music likeness', 44: 'getting email details', 45: 'playing music',
                46: 'muting audio volume', 47: 'posting on social media', 48: 'setting an alarm', 49: 'factoids',
                50: 'setting the calendar', 51: 'playing a game', 52: 'removing an alarm', 53: 'removing from lists',
                54: 'transport taxi', 55: 'movie recommendations', 56: 'making coffee', 57: 'getting music details',
                58: 'playing podcasts', 59: 'getting lists details'},
    'schema_guided_dstc8': {'Calendar_1': 'calendar', 'Homes_1': 'homes', 'Travel_1': 'travel',
                            'RentalCars_1': 'rental cars', 'Buses_1': 'buses', 'Events_2': 'events', 'Buses_2': 'buses',
                            'Events_1': 'events', 'RideSharing_1': 'ride sharing', 'Hotels_1': 'hotels',
                            'Banks_1': 'banks', 'RideSharing_2': 'ride sharing', 'Movies_1': 'movies',
                            'Media_1': 'media', 'Hotels_3': 'hotels', 'Flights_1': 'flights', 'Hotels_2': 'hotels',
                            'Music_2': 'music', 'Services_3': 'services', 'Weather_1': 'weather',
                            'Flights_2': 'flights', 'Services_1': 'services', 'Music_1': 'music',
                            'RentalCars_2': 'rental cars', 'Restaurants_1': 'restaurants', 'Services_2': 'services',
                            'Banks_2': 'banks', 'Flights_3': 'flights', 'Hotels_4': 'hotels', 'Media_2': 'media',
                            'Movies_2': 'movies', 'Restaurants_2': 'restaurants', 'Services_4': 'services',
                            'Alarm_1': 'alarm', 'Payment_1': 'payment', 'Movies_3': 'movies', 'Music_3': 'music',
                            'Media_3': 'media', 'Trains_1': 'trains', 'Events_3': 'events', 'Buses_3': 'buses',
                            'Messaging_1': 'messaging', 'RentalCars_3': 'rental cars', 'Flights_4': 'flights',
                            'Homes_2': 'homes'},
    'clinc150': {'translate': 'translation', 'transfer': 'transfer', 'timer': 'timer', 'definition': 'definition',
                 'meaning_of_life': 'meaning of life', 'insurance_change': 'insurance change',
                 'find_phone': 'finding a phone', 'travel_alert': 'travel alert', 'pto_request': 'pto request',
                 'improve_credit_score': 'improving credit score', 'fun_fact': 'fun fact',
                 'change_language': 'changing language', 'payday': 'payday',
                 'replacement_card_duration': 'replacement card duration', 'time': 'time',
                 'application_status': 'application status', 'flight_status': 'flight status',
                 'flip_coin': 'fliping a coin', 'change_user_name': 'changing user name',
                 'where_are_you_from': 'where you are from', 'shopping_list_update': 'shopping list update',
                 'what_can_i_ask_you': 'what i can ask you', 'maybe': 'not being sure',
                 'oil_change_how': 'how to change oil', 'restaurant_reservation': 'restaurant reservation',
                 'balance': 'balance', 'confirm_reservation': 'confirming reservation',
                 'freeze_account': 'freezing account', 'rollover_401k': 'rollover 401k', 'who_made_you': 'who made you',
                 'distance': 'distance', 'user_name': 'user name', 'timezone': 'timezone', 'next_song': 'next song',
                 'transactions': 'transactions', 'restaurant_suggestion': 'restaurant suggestion',
                 'rewards_balance': 'rewards balance', 'pay_bill': 'paying a bill',
                 'spending_history': 'spending history', 'pto_request_status': 'pto request status',
                 'credit_score': 'credit score', 'new_card': 'new card', 'lost_luggage': 'lost luggage',
                 'repeat': 'repeat', 'mpg': 'mpg', 'oil_change_when': 'when to change oil', 'yes': 'assertion',
                 'travel_suggestion': 'travel suggestion', 'insurance': 'insurance',
                 'todo_list_update': 'todo list update', 'reminder': 'reminder', 'change_speed': 'changing speed',
                 'tire_pressure': 'tire pressure', 'no': 'negation', 'apr': 'apr', 'nutrition_info': 'nutrition info',
                 'calendar': 'calendar', 'uber': 'uber', 'calculator': 'calculator', 'date': 'date',
                 'carry_on': 'carry ons', 'pto_used': 'pto used', 'schedule_maintenance': 'scheduling maintenance',
                 'travel_notification': 'travel notification', 'sync_device': 'sync device', 'thank_you': 'thank you',
                 'roll_dice': 'roll dice', 'food_last': 'food expiration', 'cook_time': 'cook time',
                 'reminder_update': 'reminder update', 'report_lost_card': 'reporting a lost card',
                 'ingredient_substitution': 'ingredient substitution', 'make_call': 'making a call', 'alarm': 'alarm',
                 'todo_list': 'todo list', 'change_accent': 'changing an accent', 'w2': 'w2', 'bill_due': 'bill due',
                 'calories': 'calories', 'damaged_card': 'damaged card', 'restaurant_reviews': 'restaurant reviews',
                 'routing': 'routing', 'do_you_have_pets': 'question about your pets',
                 'schedule_meeting': 'scheduling a meeting', 'gas_type': 'gas type', 'plug_type': 'plug type',
                 'tire_change': 'tire change', 'exchange_rate': 'exchange rate', 'next_holiday': 'next holiday',
                 'change_volume': 'changing volume', 'who_do_you_work_for': 'whom do you work for',
                 'credit_limit': 'credit limit', 'how_busy': 'waiting time',
                 'accept_reservations': 'accepting reservations', 'order_status': 'order status',
                 'pin_change': 'pin change', 'goodbye': 'goodbye', 'account_blocked': 'account blocked',
                 'what_song': 'what song', 'international_fees': 'international fees',
                 'last_maintenance': 'last maintenance', 'meeting_schedule': 'meeting schedule',
                 'ingredients_list': 'ingredients list', 'report_fraud': 'reporting fraud',
                 'measurement_conversion': 'measurement conversion', 'smart_home': 'smart home',
                 'book_hotel': 'booking a hotel', 'current_location': 'current location', 'weather': 'weather',
                 'taxes': 'taxes', 'min_payment': 'min payment', 'whisper_mode': 'whisper mode', 'canceling': 'cancel',
                 'international_visa': 'international visa', 'vaccines': 'vaccines', 'pto_balance': 'pto balance',
                 'directions': 'directions', 'spelling': 'spelling', 'greeting': 'greeting',
                 'reset_settings': 'reset settings', 'what_is_your_name': 'what your name is',
                 'direct_deposit': 'direct deposit', 'interest_rate': 'interest rate',
                 'credit_limit_change': 'credit limit change', 'what_are_your_hobbies': 'what your hobbies are',
                 'book_flight': 'booking a flight', 'shopping_list': 'shopping list', 'text': 'text',
                 'bill_balance': 'bill balance', 'share_location': 'sharing location',
                 'redeem_rewards': 'redeem rewards', 'play_music': 'asking to play music',
                 'calendar_update': 'calendar update', 'are_you_a_bot': 'asking if you are a bot', 'gas': 'gas',
                 'expiration_date': 'expiration date', 'update_playlist': 'updating playlist',
                 'cancel_reservation': 'canceling reservation', 'tell_joke': 'telling a joke',
                 'change_ai_name': 'changing ai name', 'how_old_are_you': 'how old you are', 'car_rental': 'car rental',
                 'jump_start': 'jump start', 'meal_suggestion': 'meal suggestion', 'recipe': 'recipe',
                 'income': 'income', 'order': 'order', 'traffic': 'traffic', 'order_checks': 'ordering checks',
                 'card_declined': 'declined card'},
    'CFPB_issue': {'Account opening, closing, or management': 'account opening, closing, or management',
                   'Account terms and changes': 'account terms and changes', 'Adding money': 'adding money',
                   'Advertising': 'advertising and marketing', 'Advertising and marketing': 'advertising and marketing',
                   'Advertising and marketing, including promotional offers': 'advertising and marketing',
                   'Advertising, marketing or disclosures': 'advertising and marketing',
                   'Application processing delay': 'application processing delay',
                   'Application, originator, mortgage broker': 'application, originator or mortgage broker',
                   'Applied for loan/did not receive money': 'loan that was approved, but no money was received',
                   'Applying for a mortgage or refinancing an existing mortgage': 'applying for a mortgage or refinancing an existing mortgage',
                   'APR or interest rate': 'apr or interest rate', 'Arbitration': 'arbitration',
                   'Attempts to collect debt not owed': 'attempts to collect debt not owed',
                   'Balance transfer': 'balance transfer', 'Balance transfer fee': 'balance transfer',
                   'Bankruptcy': 'bankruptcy', 'Billing disputes': 'billing disputes',
                   'Billing statement': 'billing statement',
                   "Can't contact lender": 'problems with a lender or other company charging your account',
                   "Can't contact lender or servicer": 'problems with a lender or other company charging your account',
                   "Can't repay my loan": 'struggling to repay a loan',
                   "Can't stop charges to bank account": 'problems with a lender or other company charging your account',
                   "Can't stop withdrawals from your bank account": 'problems with a lender or other company charging your account',
                   'Cash advance': 'problems with cash advance', 'Cash advance fee': 'problems with cash advance',
                   'Charged bank acct wrong day or amt': 'money that was taken from your bank account on the wrong day or for the wrong amount',
                   "Charged fees or interest I didn't expect": "charged fees or interest you didn't expect",
                   "Charged fees or interest you didn't expect": "charged fees or interest you didn't expect",
                   'Closing an account': 'account opening, closing, or management',
                   'Closing on a mortgage': 'closing on a mortgage',
                   'Closing your account': 'account opening, closing, or management',
                   'Closing/Cancelling account': 'account opening, closing, or management',
                   'Communication tactics': 'communication tactics',
                   'Confusing or misleading advertising or marketing': 'advertising and marketing',
                   'Confusing or missing disclosures': 'disclosures',
                   "Cont'd attempts collect debt not owed": 'continued attempts to collect debt not owed',
                   'Convenience checks': 'convenience checks',
                   'Credit card protection / Debt protection': 'credit card protection or debt protection',
                   'Credit decision / Underwriting': 'credit decision or underwriting',
                   'Credit determination': 'credit determination', 'Credit limit changed': 'changes in credit limit',
                   'Credit line increase/decrease': 'changes in credit limit',
                   'Credit monitoring or identity protection': 'credit monitoring or identity protection',
                   'Credit monitoring or identity theft protection services': 'credit monitoring or identity protection',
                   "Credit reporting company's investigation": "credit reporting company's investigation",
                   'Customer service / Customer relations': 'problems with customer service',
                   'Customer service/Customer relations': 'problems with customer service',
                   'Dealing with my lender or servicer': 'problems with a lender or other company charging your account',
                   'Dealing with your lender or servicer': 'problems with a lender or other company charging your account',
                   'Delinquent account': 'delinquent account', 'Deposits and withdrawals': 'deposits and withdrawals',
                   'Disclosure verification of debt': 'disclosure verification of debt', 'Disclosures': 'disclosures',
                   'Excessive fees': "charged fees or interest you didn't expect",
                   'False statements or representation': 'false statements or representation',
                   'Fees': "charged fees or interest you didn't expect",
                   'Fees or interest': "charged fees or interest you didn't expect",
                   'Forbearance / Workout plans': 'forbearance or workout plans', 'Fraud or scam': 'fraud or scam',
                   'Getting a credit card': 'getting a credit card',
                   'Getting a line of credit': 'getting a line of credit', 'Getting a loan': 'getting a loan or lease',
                   'Getting a loan or lease': 'getting a loan or lease', 'Getting the loan': 'getting a loan or lease',
                   'Identity theft / Fraud / Embezzlement': 'fraud or scam',
                   'Identity theft protection or other monitoring services': 'identity theft protection or other monitoring services',
                   'Improper contact or sharing of info': 'improper contact or sharing of info',
                   'Improper use of my credit report': 'improper use of your report',
                   'Improper use of your report': 'improper use of your report',
                   'Incorrect exchange rate': 'incorrect exchange rate',
                   'Incorrect information on credit report': 'incorrect information on credit report',
                   'Incorrect information on your report': 'incorrect information on credit report',
                   'Incorrect/missing disclosures or info': 'incorrect or missing disclosures or info',
                   'Late fee': 'late fee',
                   'Lender repossessed or sold the vehicle': 'lender repossessing or selling a vehicle',
                   'Loan modification,collection,foreclosure': 'loan modification, collection or foreclosure',
                   "Loan payment wasn't credited to your account": "loan payment that wasn't credited to your account",
                   'Loan servicing, payments, escrow account': 'loan servicing, payments or escrow account',
                   'Lost or stolen check': 'lost or stolen check',
                   'Lost or stolen money order': 'lost or stolen money order',
                   'Making/receiving payments, sending money': 'problems when making payments',
                   'Managing an account': 'account opening, closing, or management',
                   'Managing the line of credit': 'managing the line of credit',
                   'Managing the loan or lease': 'managing the loan or lease',
                   'Managing, opening, or closing account': 'account opening, closing, or management',
                   'Managing, opening, or closing your mobile wallet account': 'account opening, closing, or management',
                   'Money was not available when promised': 'money that was not available when promised',
                   'Money was taken from your bank account on the wrong day or for the wrong amount': 'money that was taken from your bank account on the wrong day or for the wrong amount',
                   'Opening an account': 'account opening, closing, or management',
                   'Overdraft, savings or rewards features': 'problems with overdraft',
                   'Overdraft, savings, or rewards features': 'problems with overdraft',
                   'Overlimit fee': 'overlimit fee', 'Payment to acct not credited': 'payment to account not credited',
                   'Payoff process': 'problems with the payoff process at the end of the loan', 'Privacy': 'privacy',
                   'Problem adding money': 'problems adding money',
                   'Problem caused by your funds being low': 'problems caused by your funds being low',
                   'Problem getting a card or closing an account': 'problems getting a card or closing an account',
                   'Problem when making payments': 'problems when making payments',
                   "Problem with a company's investigation into an existing issue": "problems with a company's investigation into an existing issue",
                   "Problem with a credit reporting company's investigation into an existing problem": "problems with a company's investigation into an existing issue",
                   'Problem with a lender or other company charging your account': 'problems with a lender or other company charging your account',
                   'Problem with a purchase or transfer': 'problems with a purchase or transfer',
                   'Problem with a purchase shown on your statement': 'problems with a purchase or transfer',
                   'Problem with additional add-on products or services': 'problems with additional add-on products or services',
                   'Problem with cash advance': 'problems with cash advance',
                   'Problem with customer service': 'problems with customer service',
                   'Problem with fraud alerts or security freezes': 'problems with fraud alerts or security freezes',
                   'Problem with overdraft': 'problems with overdraft',
                   'Problem with the payoff process at the end of the loan': 'problems with the payoff process at the end of the loan',
                   'Problems at the end of the loan or lease': 'problems with the payoff process at the end of the loan',
                   'Problems caused by my funds being low': 'problems caused by my funds being low',
                   'Problems when you are unable to pay': 'problems when you are unable to pay',
                   'Property was damaged or destroyed property': 'property that  was damaged or destroyed property',
                   'Property was sold': 'property was sold',
                   "Received a loan I didn't apply for": "recieving a loan you didn't apply for",
                   "Received a loan you didn't apply for": "recieving a loan you didn't apply for",
                   'Rewards': 'rewards', 'Sale of account': 'the sale of an account',
                   'Settlement process and costs': 'settlement process and costs',
                   'Shopping for a line of credit': 'getting a line of credit',
                   'Shopping for a loan or lease': 'getting a loan or lease',
                   'Struggling to pay mortgage': 'struggling to pay mortgage',
                   'Struggling to pay your bill': 'struggling to pay your bill',
                   'Struggling to pay your loan': 'struggling to repay your loan',
                   'Struggling to repay your loan': 'struggling to repay your loan',
                   'Taking out the loan or lease': 'getting a loan or lease',
                   'Taking/threatening an illegal action': 'took or threatened to take negative or legal action',
                   'Threatened to contact someone or share information improperly': 'improper contact or sharing of info',
                   'Took or threatened to take negative or legal action': 'took or threatened to take negative or legal action',
                   'Transaction issue': 'transaction issue',
                   'Trouble during payment process': 'problems when making payments',
                   'Trouble using the card': 'trouble using your card',
                   'Trouble using your card': 'trouble using your card',
                   'Unable to get credit report/credit score': 'unable to get credit report or credit score',
                   'Unable to get your credit report or credit score': 'unable to get credit report or credit score',
                   'Unauthorized transactions or other transaction problem': 'transaction issue',
                   'Unauthorized transactions/trans. issues': 'transaction issue',
                   'Unexpected or other fees': "charged fees or interest you didn't expect",
                   'Unexpected/Other fees': "charged fees or interest you didn't expect",
                   'Unsolicited issuance of credit card': 'unsolicited issuance of credit card',
                   'Using a debit or ATM card': 'using a debit or atm card',
                   'Vehicle was damaged or destroyed the vehicle': 'vehicle that was damaged or destroyed',
                   'Vehicle was repossessed or sold the vehicle': 'lender repossessing or selling a vehicle',
                   "Was approved for a loan, but didn't receive money": 'loan that was approved, but no money was received',
                   "Was approved for a loan, but didn't receive the money": 'loan that was approved, but no money was received',
                   'Written notification about debt': 'written notification about debt',
                   'Wrong amount charged or received': "charged fees or interest you didn't expect"},
    'CFPB_Product': {'Credit reporting, credit repair services, or other personal consumer reports': 'credit reporting or credit repair services or other personal consumer reports',
                     'Credit card or prepaid card': 'credit card or prepaid card',
                     'Payday loan, title loan, or personal loan': 'payday loan or title loan or personal loan',
                     'Debt collection': 'debt collection', 'Mortgage': 'mortgage',
                     'Checking or savings account': 'checking or savings account',
                     'Money transfer, virtual currency, or money service': 'money transfer or virtual currency or money service',
                     'Vehicle loan or lease': 'vehicle loan or lease',
                     'Student loan': 'student loan'},

    "financial_tweets": {
        0: "analyst update",
        1: "fed and central banks",
        2: "company and product news",
        3: "treasuries and corporate debt",
        4: "dividend",
        5: "earnings",
        6: "energy and oil",
        7: "financials",
        8: "currencies",
        9: "general News and opinion",
        10: "gold, metals and materials",
        11: "initial public offering",
        12: "legal and regulation",
        13: "mergers, acquisitions and investments",
        14: "macro",
        15: "markets",
        16: "politics",
        17: "personnel change",
        18: "stock commentary",
        19: "stock movement",
    },
    "law_stack_exchange": {'contract-law': 'contract law', 'constitutional-law': 'constitutional law',
                           'liability': 'liability', 'trademark': 'trademark', 'business': 'business',
                           'criminal-law': 'criminal law', 'privacy': 'privacy', 'tax-law': 'tax law',
                           'software': 'software', 'internet': 'internet', 'civil-law': 'civil law',
                           'intellectual-property': 'intellectual property', 'licensing': 'licensing',
                           'employment': 'employment', 'contract': 'contract', 'copyright': 'copyright'},
    "sentivent": {"cs r/brand": "brand"},
    'arxiv_dataset': {'Other Statistics': 'statistics', 'Other Quantitative Biology': 'quantitative biology',
                      'Other Computer Science': 'computer science', 'Other Condensed Matter': 'condensed matter'},
    'wiki_law_weak': {'other activities': 'activities', 'other work': 'work'}

}

user2port = {

    'ilyashn': 8794,

    'lenad': 8971,

    'alonhal': 9977,

    'avishaig': 8790,

    'oritht': 8789,

    'liate': 8793

}


def get_luigi_port_by_user():
    return user2port[os.environ['USER']]

instruct_empty_label = 'Return a list of all the matching categories or an empty list ("[]").'

prompt_config = {"flan_option_1": "{text}\n\nMulti-choice problem: What is this text about?\n{flan_options}",
                 "flan_option_2": "Choose your answer. {text}\n\nWhich topic is this text about?\n{flan_options}",
                 "flan_option_3": "{text}\nQ: Which is the best summary of this text?\n{flan_options}\nI think the answer is",
                 "flan_option_4": "{text}\nChoose your answer. What is this text about?\n{flan_options}\nAnswer:",
                 "flan_option_5": "{text}\n\nWhat best summarizes the content of the above text?\n{flan_options}",
                 "flan_option_6": "Select your answer: Which is this about?\n\n{text}\n\n{flan_options}",
                 "flan_option_7": "Select the correct answer: Which is an appropriate title for this text?\n\n{text}\n\n{flan_options}",
                 "flan_option_8": "Note the options at the end. Select the topic that this about:\n\n{text}\n\n{flan_options}",
                 "custom_option": "Classify text into categories: {class_names}.\ntext: {text}\ncategory: ",
                 "custom_option_multi_class": "Classify the text into one of the categories: {class_names}.\ntext: {text}\ncategory: ",
                 "custom_option_multi_class_with_quotation_marks": "Classify the text into one of the categories: {add_quotation_marks}.\ntext: {text}\ncategory: ",
                 "custom_option_multi_class_with_semi_colon": "Classify the text into one of the categories: {semi_colon}.\ntext: {text}\ncategory: ",
                 "custom_option_multi_class_pair_wise_option": ("Classify the text into one of the categories: {class_names}.\ntext: {text}\ncategory: ", "Classify if the following text belongs to the category {class_names}. Answer yes or no.\ntext: {text}\nanswer: "),
                 "custom_option_multi_class_custom_option_multi_class": ("Classify the text into one of the categories: {class_names}.\ntext: {text}\ncategory: ", "Classify the text into one of the categories: {class_names}.\ntext: {text}\ncategory: "),
                 "pair_wise_option": "Classify if the following text belongs to the category {class_names}. Answer yes or no.\ntext: {text}\nanswer: ",
                 "snorkel_option_1": "Pick the correct category for the text.\n\n{snorkel_options}\n\nText: {text}\nCategory: ",
                 "no_categories_to_choose": "Classify the text into a category.\ntext: {text}\ncategory: ",
                 "llama": "Classify this text into one of the following categories: {class_names}.\nText: {text}\nCategory: ",
                 "alpaca_default_multiclass" : "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nClassify the following text into one of the following categories: {class_names}.\n\n### Input:\n{text}\n\n### Response:",
                 "alpaca_pair_wise": "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nClassify the following text as {class_names} (yes) or not (no).\n\n### Input:\n{text}\n\n### Response:",
                 "custom_option_multi_class_2": "Classify the text into one of the categories: {class_names}.\nText: {text}\nCategory: ",

                 "sentiment_option_1": "Tell me the sentiment of the text. It is one of 3 categories: positive, negative, and neutral.\nText: {text}\nCategory: ",
                 "sentiment_option_2": "Tell me the sentiment of the text. It is one of 3 categories: {class_names}.\nText: {text}\nCategory: ",
                 "sentiment_option_3": "Tell me the sentiment of the text. It is one of 3 categories: negative, positive, and neutral.\nText: {text}\nCategory: ",
                 "sentiment_option_4": "Tell me the sentiment of the text. It is one of 3 categories: negative, positive, or neutral.\nText: {text}\nCategory: ",
                 "sentiment_flan_option_1g": "{text}\nWhat is the sentiment of this text?\n{flan_options}",
                 "sentiment_flan_option_1": "{text}\nWhat is the sentiment of this conversation?\n{flan_options}",
                 "sentiment_flan_option_1s": "{text}\nWhat is the sentiment of the service in this conversation?\n{flan_options}",
                 "sentiment_flan_option_2g": "Please tell me the sentiment of the following text: {text}\n{flan_options}",
                 "sentiment_flan_option_2": "Please tell me the sentiment of the following conversation: {text}\n{flan_options}",
                 "sentiment_flan_option_2s": "Please tell me the sentiment of the service in the following conversation: {text}\n{flan_options}",
                 "sentiment_flan_option_3s": "{text}\nWhat is the user's sentiment towards the agent's service in this conversation?\n{flan_options}",
                 "generative_prompt_1": {
                     'instruction_prefix': 'Classify the text into one of the categories:',
                     'input_prefix': 'Text:',
                     'output_prefix': 'Category:',
                 },
                 "generative_prompt_2": {
                     'instruction_prefix': 'Classify the text into one of the categories:',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Category: ',
                 },
                 "generative_prompt_3": {
                     'instruction_prefix': 'Classify the text into one of the categories:',
                     'input_prefix': 'Text:',
                     'output_prefix': 'Category',
                 },
                 "generative_prompt_4": {
                     'instruction_prefix': 'classify { "', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Input: ',
                     'output_prefix': 'Output: ',
                 },
                 "generative_prompt_5": {
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories. If none of the categories matches the text, please return an empty list. ',
                     'input_prefix': 'Input: ',
                     'output_prefix': 'Output: ',
                 },
                 "generative_prompt_6": {
                     'instruction_prefix': 'Classify the following text: ',
                     'input_prefix': 'Input: ',
                     'output_prefix': 'Output: ',
                 },
                 "generative_prompt_6c": {
                     'instruction_prefix': 'Classify the following text: ',
                     'input_prefix': 'Input: ',
                     'output_prefix': 'Output: ',
                 },
                 "generative_prompt_7": 'dummy',
                 "generative_prompt_8": 'dummy',
                 "generative_multilabel_prompt_9": {
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': ', ',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Input: ',
                     'output_prefix': 'Output: ',
                  },
                  "generative_multilabel_prompt_10": {
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Input: ',
                     'output_prefix': 'Output: ',
                },
                  "generative_multilabel_prompt_11": {
                     'limit_classes' : 20,
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',

                },
                
                "generative_prompt_12_ilyashn": {
                     'instruction_prefix': 'Classify the text into one or more of the categories. Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                },

                "most_generative_multilabel_prompt_13": {
                     'limit_classes' : 20,
                     'pick_method': 'most',
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                },

                "random_generative_multilabel_prompt_14": {
                     'limit_classes' : 20,
                     'pick_method': 'random',
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                },
                
                "no_classes_prompt_15": {
                    'instruction_prefix': 'Classify the text into one or more of the categories. Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                },

                "all_prompt_16": {
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',

                },

                "first_half_17": {
                    'limit_classes' : 0.5,
                    'pick_method': 'most',
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                },

                "second_half_18": {
                     'limit_classes' : 0.5,
                     'pick_method': 'least',
                     'instruction_prefix': 'Classify the text into one or more of the following categories { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                },

                '20_newsgroup_template': {
                     'instruction_prefix': 'classify the following news post into one of the topics: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Post: ',
                     'output_prefix': 'Topic: ',
                 },

                 'CFPB_Product_template': {
                     'instruction_prefix': 'classify the following consumer complaint into one of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Complaint: ',
                     'output_prefix': 'Category: ',
                 },
                
                'news_category_classification_headline_template': {
                     'instruction_prefix': 'classify the following news headline into one of the topics: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Headline: ',
                     'output_prefix': 'Topic: ',
                 },

                'watson_sentiment_template': {
                     'instruction_prefix': 'classify the sentiment of the following text as either "positive", "negative" or "neutral". ', 
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Sentiment: ',
                 },

                 'q2c-india_template': {
                     'instruction_prefix': 'classify the following email thread into one of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Email thread: ',
                     'output_prefix': 'Category: ',
                 },
 # argument_topic banking77 claim_stance_topic clinc150 ledgar
                  'clinc150_template': {
                     'instruction_prefix': 'classify the following query into one of the intents: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Query: ',
                     'output_prefix': 'Intent: ',
                 },

                 'banking77_template': {
                     'instruction_prefix': 'classify the following banking query into one of the intents: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Query: ',
                     'output_prefix': 'Intent: ',
                 },

                'ledgar_template': {
                     'instruction_prefix': 'classify the following contract provision into one of the topics: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Contract provision: ',
                     'output_prefix': 'Topic: ',
                 },

                 'argument_topic_template': {
                     'instruction_prefix': 'classify the following argument into one of the topics: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Argument: ',
                     'output_prefix': 'Topic: ',
                 },

                 
                'claim_stance_topic_template': {
                     'instruction_prefix': 'classify the following claim into one of the topics: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Claim: ',
                     'output_prefix': 'Topic: ',
                 },
                 'SEC_10k_template': {
                     'instruction_prefix': 'classify the following financial statement into one of the topics: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"}',
                     'input_prefix': 'Statement: ',
                     'output_prefix': 'Topic: ',
                 },

                "classify_second_half_28": {
                     'limit_classes' : 0.5,
                     'pick_method': 'least',
                     'instruction_prefix': 'classify { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                },

                'general_template': {
                     'instruction_prefix': 'Classify the text into one or more of the following categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                 },

                'cat_template': {
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                 },

                'cc_tone_template': {
                     'instruction_prefix': 'Classify the following customer care tweets into one or more of the emotions: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Tweet: ',
                     'output_prefix': 'Emotions: ',
                 },

                'contract_nli_template': {
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories. ',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                 },

                'reuters21578_template': {
                     'instruction_prefix': 'Classify the following financial article into one or more of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Article: ',
                     'output_prefix': 'Categories: ',
                 },

                'sentivent_template': {
                     'instruction_prefix': 'Classify the following financial text into one or more of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Categories: ',
                 },

                'unfair_tos_template': {
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                 },

                'watson_emotion_template': {
                     'instruction_prefix': 'Classify the following text into one of the emotions: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Text: ',
                     'output_prefix': 'Emotion: ',
                 },

                "cuad_template": {
                     'limit_classes' : 0.5,
                     'pick_method': 'least',
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories.',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                },

                "q2c_nda_eho_template": {
                     'limit_classes' : 0.5,
                     'pick_method': 'least',
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories.',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                },
                
                "cuad_2_template": {
                     'limit_classes' : 0.5,
                     'pick_method': 'least',
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                },

                "q2c_nda_eho_2_template": {
                     'limit_classes' : 0.5,
                     'pick_method': 'least',
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { "',
                     'class_separator': '", "',
                     'instruction_suffix':  '"} . Return a list of all the matching categories or an empty list ("[]").',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                },

                'contract_nli_2_template': {
                     'instruction_prefix': 'Classify the following legal contract clause into one or more of the categories: { ', 
                     'class_separator': '", "',
                     'instruction_suffix':  '"} Return a list of all the matching categories or an empty list ("[]"). ',
                     'input_prefix': 'Contract clause: ',
                     'output_prefix': 'Categories: ',
                 },

                "generative_prompt_36": {
                     'instruction_prefix': 'Classify the following text: ',
                     'input_prefix': 'Input: ',
                     'output_prefix': 'Output: ',
                 },

                  'clinc150_3_template': {
                     'instruction_prefix': 'classify the following query into one of the intents: { ', 
                     'instruction_suffix':  '',
                     'input_prefix': 'Query: ',
                     'output_prefix': 'Intent: ',
                 },
                
                 'clinc150_4_template': {
                     'instruction_prefix': 'classify the following query into one of the intents: ', 
                     'instruction_suffix':  '',
                     'input_prefix': 'Query: ',
                     'output_prefix': 'Intent: ',
                 },

                 'clinc150_5_template': {
                     'instruction_prefix': 'classify the following query into one of the intents: {}', 
                     'instruction_suffix':  '',
                     'input_prefix': 'Query: ',
                     'output_prefix': 'Intent: ',
                 },
                 'banking77_3_template': {
                     'instruction_prefix': 'classify the following banking query into one of the intents. ', 
                     'instruction_suffix':  '',
                     'input_prefix': 'Query: ',
                     'output_prefix': 'Intent: ',
                 },

                'ledgar_3_template': {
                     'instruction_prefix': 'classify the following contract provision into one of the topics. ', 
                     'instruction_suffix':  '',
                     'input_prefix': 'Contract provision: ',
                     'output_prefix': 'Topic: ',
                 },

                 'argument_topic_3_template': {
                     'instruction_prefix': 'classify the following argument into one of the topics. ', 
                     'instruction_suffix':  '',
                     'input_prefix': 'Argument: ',
                     'output_prefix': 'Topic: ',
                 },

                 
                'claim_stance_topic_3_template': {
                     'instruction_prefix': 'classify the following claim into one of the topics. ', 
                     'instruction_suffix':  '',
                     'input_prefix': 'Claim: ',
                     'output_prefix': 'Topic: ',
                 },
 
            }
