from itertools import product
from datasets import load_dataset
from unitxt import add_to_catalog
from pathlib import Path

from unitxt.blocks import (
    LoadHF,
    SplitRandomMix,
    AddFields,
    TaskCard,
    NormalizeListFields,
    FormTask,
    TemplatesList,
    InputOutputTemplate,
    MapInstanceValues,
    RenameFields
)
keep_labels = [
  "copper",
  "interest",
  "gold",
  "ships",
  "crude",
  "acquisition",
  "jobs",
  "grain",
  "trade",
  "gross national product",
  "cocoa",
  "money foreign exchange",
  "coffee",
  "money supply",
  "oilseed",
  "vegetable oil",
  "livestock",
  "sugar",
  "earnings",
  "consumer price index"
]

dataset_name = 'reuters21578'

our_mappings = {
    'pet-chem': 'pet chem',
 'income': 'income',
 'strategic-metal': 'strategic metal',
 'lei': 'lei',
 'rand': 'rand',
 'livestock': 'livestock',
 'gold': 'gold',
 'coconut-oil': 'coconut oil',
 'rupiah': 'rupiah',
 'nkr': 'nkr',
 'oat': 'oat',
 'propane': 'propane',
 'saudriyal': 'saudriyal',
 'sorghum': 'sorghum',
 'tea': 'tea',
 'cotton-oil': 'cotton oil',
 'nat-gas': 'nat gas',
 'fuel': 'fuel',
 'citruspulp': 'citruspulp',
 'nzdlr': 'nzdlr',
 'stg': 'stg',
 'sun-meal': 'sun meal',
 'cruzado': 'cruzado',
 'dfl': 'dfl',
 'castorseed': 'castorseed',
 'rice': 'rice',
 'cornglutenfeed': 'cornglutenfeed',
 'cpi': 'consumer price index',
 'meal-feed': 'meal feed',
 'wheat': 'wheat',
 'crude': 'crude',
 'gnp': 'gross national product',
 'ship': 'ships',
 'acq': 'acquisition',
 'barley': 'barley',
 'cottonseed': 'cottonseed',
 'lin-oil': 'lin oil',
 'corn-oil': 'corn oil',
 'silver': 'silver',
 'soy-meal': 'soy meal',
 'tapioca': 'tapioca',
 'orange': 'orange',
 'plywood': 'plywood',
 'lead': 'lead',
 'tin': 'tin',
 'f-cattle': 'f cattle',
 'sfr': 'sfr',
 'linseed': 'linseed',
 'sugar': 'sugar',
 'pork-belly': 'pork belly',
 'jobs': 'jobs',
 'naphtha': 'naphtha',
 'rye': 'rye',
 'lumber': 'lumber',
 'interest': 'interest',
 'dkr': 'dkr',
 'platinum': 'platinum',
 'money-supply': 'money supply',
 'rape-meal': 'rape meal',
 'coconut': 'coconut',
 'gas': 'gas',
 'heat': 'heat',
 'retail': 'retail',
 'ipi': 'ipi',
 'ringgit': 'ringgit',
 'copra-cake': 'copra cake',
 'zinc': 'zinc',
 'rapeseed': 'rapeseed',
 'cpu': 'cpu',
 'lit': 'lit',
 'fishmeal': 'fishmeal',
 'soy-oil': 'soy oil',
 'veg-oil': 'vegetable oil',
 'yen': 'yen',
 'carcass': 'carcass',
 'lin-meal': 'lin meal',
 'red-bean': 'red bean',
 'jet': 'jet',
 'wpi': 'wpi',
 'castor-oil': 'castor oil',
 'copper': 'copper',
 'coffee': 'coffee',
 'wool': 'wool',
 'cocoa': 'cocoa',
 'groundnut-oil': 'groundnut oil',
 'peseta': 'peseta',
 'palm-oil': 'palm oil',
 'dmk': 'dmk',
 'bop': 'bop',
 'l-cattle': 'l cattle',
 'oilseed': 'oilseed',
 'instal-debt': 'instal debt',
 'grain': 'grain',
 'iron-steel': 'iron steel',
 'reserves': 'reserves',
 'rubber': 'rubber',
 'rape-oil': 'rape oil',
 'housing': 'housing',
 'inventories': 'inventories',
 'potato': 'potato',
 'hog': 'hog',
 'trade': 'trade',
 'earn': 'earnings',
 'skr': 'skr',
 'sun-oil': 'sun oil',
 'palladium': 'palladium',
 'sunseed': 'sunseed',
 'dlr': 'dlr',
 'can': 'can',
 'soybean': 'soybean',
 'corn': 'corn',
 'cotton': 'cotton',
 'austdlr': 'austdlr',
 'palmkernel': 'palmkernel',
 'groundnut': 'groundnut',
 'alum': 'alum',
 'money-fx': 'money foreign exchange',
 'nickel': 'nickel'}

label_names = list(our_mappings.keys())

additional_cases = [
    ['grain', 'oilseed', 'wheat', 'rapeseed'],
['trade', 'livestock', 'carcass', 'sugar'],
['grain', 'wheat', 'cotton', 'soybean', 'soy-oil', 'veg-oil', 'oilseed', 'soy-meal', 'meal-feed'],
['money-fx', 'dlr', 'yen', 'bop', 'gnp'],
['grain', 'rice', 'wheat', 'sorghum'],
['grain', 'wheat', 'oilseed', 'soybean'],
['coffee', 'oilseed', 'soybean', 'trade', 'sugar', 'cocoa'],
['oilseed', 'soybean', 'grain', 'corn', 'wheat'],
['grain', 'wheat', 'corn', 'sugar', 'carcass', 'livestock', 'groundnut', 'oilseed', 'cotton', 'veg-oil'],
['wheat', 'barley', 'corn', 'rapeseed', 'grain', 'oilseed', 'ship'],
['heat', 'naphtha', 'jet', 'fuel'],
['grain', 'oat', 'corn', 'oilseed', 'soybean'],
['grain', 'wheat', 'corn', 'cotton', 'sorghum', 'barley', 'corn'],
['jobs', 'ipi', 'gnp', 'income', 'trade', 'retail'],
['money-fx', 'dlr', 'trade', 'acq'],
['grain', 'corn', 'oilseed', 'soybean', 'veg-oil', 'soy-oil', 'meal-feed', 'soy-meal', 'cotton'],
['oilseed', 'soybean', 'soy-meal', 'veg-oil', 'soy-oil'],
['oilseed', 'soybean', 'veg-oil', 'palm-oil', 'palmkernel', 'coconut-oil'],
['grain', 'oilseed', 'meal-feed', 'veg-oil'],
['gold', 'silver', 'zinc', 'lead'],
['grain', 'corn', 'soybean', 'oilseed'],
['crude', 'gas', 'nat-gas', 'wpi'],
['trade', 'bop', 'money-fx', 'crude', 'gnp', 'dlr'],
['grain', 'oilseed', 'meal-feed', 'veg-oil', 'corn', 'wheat', 'soybean', 'soy-oil', 'soy-meal', 'cotton', 'rice', 'sorghum', 'barley', 'oat'],
['palm-oil', 'palmkernel', 'oilseed', 'veg-oil'],
['trade', 'coffee', 'rubber', 'palm-oil'],
['gnp', 'trade', 'jobs', 'retail'],
['veg-oil', 'grain', 'corn', 'wheat'],
['grain', 'oilseed', 'sunseed', 'corn', 'soybean', 'sorghum'],
['trade', 'carcass', 'orange', 'rice'],
['livestock', 'l-cattle', 'carcass', 'sugar'],
['grain', 'oilseed', 'corn', 'soybean'],
['trade', 'bop', 'money-fx', 'dlr'],
['grain', 'cotton', 'wheat', 'oat', 'oilseed', 'soybean'],
['trade', 'hog', 'carcass', 'livestock'],
['acq', 'gold', 'silver', 'zinc', 'lead'],
['trade', 'cotton', 'grain', 'corn', 'wheat', 'oilseed'],
['copper', 'sugar', 'grain', 'corn'],
['acq', 'oilseed', 'sunseed', 'soybean'],
['money-fx', 'dlr', 'stg', 'skr', 'nkr', 'dkr', 'dmk'],
['corn', 'sunseed', 'soybean', 'grain', 'oilseed'],
['oilseed', 'soybean', 'meal-feed', 'soy-meal'],
['grain', 'corn', 'cornglutenfeed', 'meal-feed'],
['oilseed', 'rapeseed', 'grain', 'wheat', 'corn', 'palm-oil', 'soy-oil', 'ship'],
['copper', 'lead', 'zinc', 'strategic-metal'],
['grain', 'corn', 'sorghum', 'oilseed', 'sunseed', 'soybean'],
['oilseed', 'cotton', 'wheat', 'grain', 'sunseed', 'linseed', 'rapeseed', 'soybean', 'groundnut'],
['oilseed', 'soybean', 'grain', 'wheat', 'corn'],
['grain', 'wheat', 'oilseed', 'sunseed'],
['interest', 'money-fx', 'dfl', 'dmk'],
['grain', 'corn', 'oilseed', 'soybean', 'soy-meal', 'meal-feed', 'veg-oil', 'soy-oil', 'cotton', 'sorghum', 'cotton-oil', 'barley', 'oat', 'rice'],
['trade', 'sugar', 'cotton', 'groundnut', 'oilseed'],
['grain', 'meal-feed', 'wheat', 'corn', 'soy-meal'],
['grain', 'wheat', 'corn', 'sorghum', 'cotton'],
['grain', 'corn', 'wheat', 'soybean', 'oilseed', 'barley', 'sorghum', 'cotton', 'rice'],
['veg-oil', 'coconut', 'copra-cake', 'meal-feed', 'palm-oil', 'coconut-oil'],
['trade', 'grain', 'wheat', 'coffee', 'tea', 'iron-steel', 'crude'],
['trade', 'bop', 'interest', 'money-fx'],
['grain', 'oilseed', 'soybean', 'carcass', 'corn', 'cotton', 'rice'],
['interest', 'reserves', 'jobs', 'income'],
['trade', 'cotton', 'iron-steel', 'naphtha', 'veg-oil', 'palm-oil'],
['trade', 'grain', 'rice', 'cotton'],
['grain', 'oilseed', 'veg-oil', 'sorghum', 'sun-meal', 'lin-oil', 'groundnut-oil', 'soy-oil', 'rape-oil', 'sun-oil', 'wheat', 'meal-feed'],
['grain', 'rice', 'wheat', 'tea', 'sugar'],
['wpi', 'gas', 'nat-gas', 'crude', 'heat'],
['grain', 'meal-feed', 'carcass', 'soy-meal', 'livestock'],
['cotton', 'sugar', 'veg-oil', 'grain'],
['money-fx', 'grain', 'cotton', 'livestock', 'gold', 'silver'],
['trade', 'wpi', 'cpi', 'income', 'retail'],
['veg-oil', 'sun-oil', 'corn-oil', 'rape-oil'],
['trade', 'gnp', 'bop', 'dlr'],
['oilseed', 'sunseed', 'soybean', 'rapeseed', 'veg-oil', 'soy-oil', 'palm-oil', 'groundnut-oil'],
['grain', 'wheat', 'corn', 'sorghum', 'barley', 'oat'],
['dlr', 'money-fx', 'trade', 'cpi', 'money-supply'],
['grain', 'wheat', 'rice', 'veg-oil', 'soybean', 'sugar', 'rubber', 'copra-cake', 'corn', 'palm-oil', 'palmkernel', 'coffee', 'tea', 'plywood', 'soy-meal', 'cotton'],
['gnp', 'jobs', 'cpi', 'bop', 'dfl'],
['grain', 'corn', 'wheat', 'barley'],
['meal-feed', 'sun-meal', 'lin-meal', 'soy-meal'],
['grain', 'barley', 'wheat', 'corn', 'oilseed', 'rapeseed'],
['gold', 'silver', 'copper', 'alum'],
['interest', 'gnp', 'ipi', 'wpi'],
['veg-oil', 'soy-oil', 'oilseed', 'soybean'],
['veg-oil', 'oilseed', 'meal-feed', 'soybean', 'soy-oil', 'soy-meal'],
['bop', 'trade', 'austdlr', 'money-fx', 'interest'],
['retail', 'jobs', 'gnp', 'inventories', 'trade', 'cpi'],
['oilseed', 'veg-oil', 'castorseed', 'castor-oil'],
['trade', 'livestock', 'carcass', 'grain', 'wheat'],
['cpi', 'crude', 'nat-gas', 'heat', 'propane'],
['oilseed', 'rapeseed', 'soybean', 'sunseed'],
['wheat', 'corn', 'soybean', 'grain', 'oilseed'],
['grain', 'wheat', 'oilseed', 'rapeseed'],
['grain', 'wheat', 'wool', 'dlr'],
['grain', 'wheat', 'oilseed', 'soybean', 'veg-oil'],
['grain', 'cotton', 'rice', 'oilseed', 'soybean'],
['meal-feed', 'soy-meal', 'grain', 'corn'],
['grain', 'corn', 'oilseed', 'soybean', 'sorghum', 'sunseed'],
['cocoa', 'coffee', 'sugar', 'heat'],
['grain', 'wheat', 'barley', 'corn'],
['veg-oil', 'soybean', 'oilseed', 'meal-feed', 'soy-meal'],
['gold', 'platinum', 'palladium', 'copper', 'nickel'],
['money-fx', 'rupiah', 'dmk', 'yen'],
['gold', 'zinc', 'lead', 'silver'],
['grain', 'wheat', 'soybean', 'oilseed'],
['meal-feed', 'soy-meal', 'oilseed', 'soybean', 'sunseed', 'rapeseed'],
['trade', 'rice', 'livestock', 'carcass', 'grain', 'corn', 'oilseed', 'soybean'],
['veg-oil', 'grain', 'wheat', 'cotton'],
['grain', 'wheat', 'oat', 'barley'],
['grain', 'wheat', 'corn', 'oilseed', 'soybean', 'meal-feed', 'soy-meal', 'veg-oil', 'soy-oil', 'cotton', 'rice'],
['veg-oil', 'linseed', 'lin-oil', 'soy-oil', 'sun-oil', 'soybean', 'oilseed', 'corn', 'sunseed', 'grain', 'sorghum', 'wheat'],
['ship', 'grain', 'oilseed', 'veg-oil', 'meal-feed'],
['grain', 'corn', 'wheat', 'oilseed', 'soybean'],
['grain', 'rye', 'wheat', 'barley', 'oat', 'oilseed', 'rapeseed', 'sugar'],
['grain', 'barley', 'oilseed', 'rapeseed'],
['grain', 'wheat', 'oilseed', 'soybean', 'cotton', 'rice'],
['grain', 'wheat', 'corn', 'sorghum'],
['money-fx', 'dlr', 'yen', 'dmk'],
['soybean', 'grain', 'wheat', 'corn'],
['trade', 'grain', 'rice', 'corn', 'sugar', 'tin', 'rubber'],
['acq', 'gold', 'silver', 'lead', 'zinc'],
['veg-oil', 'palm-oil', 'soy-oil', 'oilseed', 'soybean'],
['grain', 'corn', 'sorghum', 'sunseed', 'oilseed'],
['veg-oil', 'palm-oil', 'rape-oil', 'ship'],
['oilseed', 'grain', 'soybean', 'wheat', 'corn'],
['grain', 'corn', 'sugar', 'rubber'],
['grain', 'corn', 'sorghum', 'sunseed', 'wheat', 'oilseed', 'soybean'],
['copper', 'lead', 'zinc', 'silver', 'nickel', 'alum'],
['grain', 'wheat', 'corn', 'barley'],
['grain', 'wheat', 'corn', 'oat', 'rye', 'sorghum', 'soybean', 'oilseed'],
['meal-feed', 'livestock', 'carcass', 'grain', 'corn', 'sorghum', 'oilseed', 'soy-meal', 'rapeseed'],
['grain', 'wheat', 'corn', 'soybean', 'oilseed'],
['grain', 'corn', 'wheat', 'oilseed'],
['tin', 'sugar', 'grain', 'wheat', 'cocoa', 'coffee', 'rubber'],
['grain', 'sugar', 'carcass', 'livestock'],
['grain', 'wheat', 'soybean', 'corn', 'sorghum', 'oilseed', 'sunseed'],
['grain', 'corn', 'oilseed', 'soybean'],
['gnp', 'cpi', 'reserves', 'grain'],
['money-fx', 'dlr', 'yen', 'can', 'stg'],
['tin', 'veg-oil', 'palm-oil', 'alum'],
['veg-oil', 'palm-oil', 'soy-oil', 'rape-oil', 'cotton-oil', 'coconut-oil', 'sun-oil'],
['grain', 'sugar', 'livestock', 'carcass'],
['oilseed', 'soybean', 'veg-oil', 'trade'],
['grain', 'corn', 'wheat', 'oilseed', 'soybean', 'meal-feed', 'veg-oil', 'soy-oil', 'sorghum', 'barley'],
['gnp', 'interest', 'money-fx', 'trade'],
['grain', 'rice', 'corn', 'cotton', 'wheat', 'sorghum', 'barley', 'oat'],
['trade', 'bop', 'rubber', 'veg-oil', 'palm-oil'],
['grain', 'wheat', 'corn', 'oilseed', 'soybean'],
['oilseed', 'sunseed', 'rapeseed', 'veg-oil', 'sun-oil', 'rape-oil'],
['grain', 'corn', 'rice', 'oilseed', 'soybean', 'orange'],
['gold', 'platinum', 'palladium', 'nickel', 'copper'],
['meal-feed', 'soy-meal', 'tapioca', 'grain', 'corn', 'cornglutenfeed', 'citruspulp', 'oilseed', 'rapeseed', 'rape-meal'],
['grain', 'potato', 'wheat', 'barley', 'meal-feed', 'soy-meal', 'hog', 'carcass', 'livestock'],
['interest', 'trade', 'gnp', 'bop', 'cpi'],
['gnp', 'jobs', 'bop', 'cpi'],
['oilseed', 'soybean', 'veg-oil', 'palm-oil', 'coconut-oil'],
['trade', 'tea', 'coffee', 'cotton', 'castor-oil'],
['money-fx', 'dlr', 'yen', 'interest'],
['grain', 'oilseed', 'soy-oil', 'corn'],
['grain', 'corn', 'oilseed', 'livestock'],
['trade', 'money-fx', 'cpi', 'reserves'],
['grain', 'corn', 'rice', 'oilseed', 'cottonseed', 'groundnut'],
['meal-feed', 'grain', 'corn', 'sorghum', 'oilseed', 'soybean'],
['silver', 'copper', 'lead', 'zinc', 'gold', 'strategic-metal'],
['grain', 'wheat', 'corn', 'sorghum', 'barley'],
['grain', 'rice', 'corn', 'cotton'],
['grain', 'wheat', 'corn', 'barley', 'oat', 'sorghum'],
['trade', 'bop', 'interest', 'stg', 'money-fx'],
['pet-chem', 'crude', 'acq', 'earn'],
['grain', 'wheat', 'cotton', 'rice'],
['oilseed', 'soybean', 'soy-meal', 'meal-feed'],
['grain', 'wheat', 'corn', 'sorghum', 'oat'],
['grain', 'oilseed', 'meal-feed', 'veg-oil', 'wheat', 'corn', 'soybean', 'soy-oil', 'soy-meal', 'cotton'],
['grain', 'corn', 'sorghum', 'sunseed', 'oilseed', 'soybean'],
['trade', 'grain', 'wheat', 'tea', 'coffee', 'iron-steel', 'crude'],
['grain', 'corn', 'wheat', 'rice'],
['gold', 'silver', 'copper', 'zinc', 'lead'],
['veg-oil', 'palm-oil', 'lumber', 'coffee', 'rubber'],
['grain', 'barley', 'corn', 'wheat'],
['grain', 'ship', 'wheat', 'barley'],
]

map_labels = {
    '[]': [], # 0 elements

    **{str(list(vector)): [our_mappings[x] for x in vector if x in keep_labels] for vector in product(label_names)}, # 1 element
    **{str(list(vector)): [our_mappings[x] for x in vector if x in keep_labels ] for vector in product(label_names, label_names)}, # 2 elements
    **{str(list(vector)): [our_mappings[x] for x in vector if x in keep_labels] for vector in product(label_names, label_names, label_names)},

    **{str(vector):[our_mappings[x] for x in vector] for vector in additional_cases}
}
card = TaskCard(    
    loader=LoadHF(path=f'{dataset_name}', name='ModApte'),
    preprocess_steps=[
        SplitRandomMix(
            {'train': 'train[85%]', 'dev': 'train[15%]', 'test': 'test'}),
        RenameFields(field_to_field={"topics": "labels"}),
        MapInstanceValues(mappers= {'labels': map_labels}),
        
    ],
    task=FormTask(
        inputs=["text"],
        outputs=["labels"],
        metrics=["metrics.f1_micro",
                 "metrics.accuracy", "metrics.f1_macro"],
    ),
    templates=TemplatesList([
        InputOutputTemplate(
            input_format='{text}',
            output_format='{labels}',
        ),
    ])
)

add_to_catalog(artifact=card, name=f'cards.{dataset_name}', overwrite=True)
#ds = load_dataset(f'unitxt/data', f'card=cards.{dataset_name},template_card_index=0')
#print(ds['dev']['additional_inputs'][0])